---
- name: Mongodb-org repository
  yum_repository:
    name: mongodb-org-3.4
    description: MongoDB Repository
    file: mongodb-org
    baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/3.4/x86_64/
    gpgcheck: true
    gpgkey: https://www.mongodb.org/static/pgp/server-3.4.asc
    enabled: true

- name: Uninstall packages from epel
  package:
    name:
      - mongodb
      - mongodb-server
    state: absent

- name: Install packages
  package:
    name:
      - mongodb-org
      - mongodb-org-server
      - mongodb-org-shell
      - mongodb-org-tools

- name:
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
  notify: restart mongod

- name: Start / enable mongod
  systemd:
    name: mongod
    enabled: yes

- name: firewall new connections
  iptables:
    chain: INPUT
    action: insert
    protocol: tcp
    ctstate: NEW
    destination_port: "{{ mongodb_port }}"
    jump: ACCEPT

- name: firewall related, established connections
  iptables:
    chain: INPUT
    action: insert
    ctstate: RELATED,ESTABLISHED
    jump: ACCEPT
